version: '3'

services:
  web:
    build: .
    ports:
      - "5000:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./downloaded_content:/app/downloaded_content
    restart: unless-stopped
